name: Feature Request
description: Request a new feature for Kahi UI
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        If you intend to submit a PR for this issue, mention that in the description. Thanks!
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the Request
      description: Provide a clear description of the issue you're facing and your proprosed solution.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Mention anything not covered above or something you think might be important.
