const CSSNANO_PRESET = {
    // TODO: Configure for basically just white space and any aesthetic minifications
    autoprefixer: false,
    cssDeclarationSorter: false,
    rawCache: false,
    calc: false,
    colormin: false,
    convertValues: false,
    discardComments: false,
    discardDuplicates: false,
    discardEmpty: false,
    discardOverridden: false,
    discardUnused: false,
    mergeIdents: false,
    mergeLonghand: false,
    mergeRules: false,
    minifyFontValues: false,
    minifyGradients: false,
    minifyParams: false,
    minifySelectors: false,
    normalizeCharset: false,
    normalizeDisplayValues: false,
    normalizePositions: false,
    normalizeRepeatStyle: false,
    normalizeString: false,
    normalizeTimingFunctions: false,
    normalizeUnicode: false,
    normalizeUrl: false,
    normalizeWhitespace: false,
    orderedValues: false,
    reduceIdents: false,
    reduceInitial: false,
    reduceTransforms: false,
    svgo: false,
    uniqueSelectors: false,
    zindex: false,
};

module.exports = {
    plugins: [
        require("cssnano")({
            preset: ["default", CSSNANO_PRESET],
        }),
    ],
};
